[en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[zh]
title = "我的博客"
description = "一名中科大的本科生"
contentDir = "content/chinese" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "中"
