  [[main]]
  name = "主站"
  identifier = "main"
  weight = 100
  url = "/zh/"

  [[main]]
  name = "博客"
  weight = 200
  identifier = "posts"
  url = "/zh/post/"

  [[main]]
  name = "关于"
  weight = 300
  identifier = "about"
  url = "/zh/about/"

  [[main]]
  name = "联系"
  weight = 400
  identifier = "contact"
  url = "/zh/contact/"